
import json
import sys
from pathlib import Path

def generate_commands():
    output_dir = Path("output")
    if not output_dir.exists():
        print("Output directory not found!")
        return

    commands = []
    print("#!/bin/bash\n")
    print("# Commands to regenerate analysis for all brands using stored parameters")
    print("# Generated by Antigravity\n")

    for brand_dir in sorted(output_dir.iterdir()):
        if not brand_dir.is_dir() or brand_dir.name.startswith("."):
            continue
        
        json_path = brand_dir / f"{brand_dir.name}.json"
        if not json_path.exists():
            print(f"# Warning: No JSON found for {brand_dir.name}, skipping...")
            continue
            
        try:
            with open(json_path) as f:
                data = json.load(f)
            
            product_info = data.get("product_info", {})
            weight = product_info.get("weight_kg")
            price = product_info.get("price_inr")
            
            if weight is None or price is None:
                print(f"# Warning: Missing weight/price for {brand_dir.name}, skipping...")
                continue
                
            cmd = f"analyse full images/{brand_dir.name} -w {weight} -p {price} --push --force"
            print(cmd)
            
        except Exception as e:
            print(f"# Error reading {brand_dir.name}: {e}")

if __name__ == "__main__":
    generate_commands()
