#!/bin/bash

# Commands to regenerate analysis for all brands using stored parameters
# Generated by Antigravity

analyse full images/CosmixPlantProtein -w 1.0 -p 2122.0 --push --force
analyse full images/ON_vanilla -w 0.907 -p 3199.0 --push --force
analyse full images/OriginPlantProtein -w 0.975 -p 2379.0 --push --force
analyse full images/happycultures -w 0.505 -p 999.0 --push --force
analyse full images/millePlantProtein -w 0.5 -p 1436.0 --push --force
analyse full images/muscle_blaze -w 1.0 -p 2299.0 --push --force
analyse full images/oziva -w 0.5 -p 1299.0 --push --force
analyse full images/superyou -w 1.0 -p 2249.0 --push --force
analyse full images/truebasics -w 1.0 -p 2399.0 --push --force
analyse full images/trunativ -w 0.907 -p 2799.0 --push --force
analyse full images/wellbeing -w 1.0 -p 2398.0 --push --force
analyse full images/wholetruth -w 1.0 -p 2538.0 --push --force
